<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="OAuth2 Authorization Login">
    <meta name="author" content="James Stormes">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; style-src https://*; child-src 'none'; require-sri-for style;">
    <link rel="icon" href="/favicon.ico">

    <title>OAuth2 Sign In</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="/signin.css" rel="stylesheet">
</head>

<body class="text-center">
<form class="form-signin" method="post">
    <?php if (isset($this->data['error_msg'])): ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $this->data['error_msg'] ?>
        </div>
    <?php else: ?>
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <?php endif ?>
    <label for="username" class="sr-only">Email address</label>
    <input type="email" id="username" name="username" class="form-control" placeholder="Email address"
           value="<?php echo $this->data['username']; ?>" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>
</body>
</html>