<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="OAuth2 Authorization Login">
    <meta name="author" content="James Stormes">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; style-src https://*; child-src 'none'; require-sri-for style;">
    <link rel="icon" href="/favicon.ico">

    <title>OAuth2 Sign Out</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="/signin.css" rel="stylesheet">
</head>

<body class="text-center">
<form class="form-signin" method="post">
    <div class="alert alert-primary" role="alert">
        You have been signed out.
    </div>
</form>
</body>
</html>